version: "3.7"
services:
  arangodb_db_container:
    image: arangodb:latest
    environment:
      ARANGO_NO_AUTH: 1
    ports:
      - 8529:8529
    volumes:
      - ./volume/db:/var/lib/arangodb3
      - ./volume/apps:/var/lib/arangodb3-apps
